"""empty message

Revision ID: 048f12ad6aa5
Revises: 
Create Date: 2021-09-03 10:13:44.350567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048f12ad6aa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
